NTUE-Arduino-Lab/DTD-official-website

package-lock.json, package.json, src/layouts/Home/index.js
=> feat: add react-helmet

src/layouts/Home/index.js, src/layouts/Home/styles.module.scss
=> index background color

src/layouts/Home/index.js, src/layouts/Home/styles.module.scss, src/styles/media.scss, src/styles/spacing.scss
index rwd
index icon
index banner height
=> Home screen v3

mu-plugins/dtd-post-types.php, mu-plugins/functions.php, mu-plugins/search-route.php
=> mu-plugin update

mu-plugins/search-route.php
=> add staff api

src/assets/json/admissions.json, src/components/Admissions/index.js, src/components/Admissions/styles.module.scss, src/components/Header/index.js, src/layouts/College/index.js, src/layouts/College/styles.module.scss, src/layouts/Inservice/index.js, src/layouts/Inservice/styles.module.scss, src/layouts/Master/index.js, src/layouts/Master/styles.module.scss, src/routes/index.js, src/uiStore/reducer.js, src/utils/path.js
=> Admissions page

src/components/Header/index.js, src/store/actions.js
修正action.js的錯誤，header新增系上活動、未來發展的連結
=> fix: actions.js error, feat: header path

mu-plugins/dtd-post-types.php, mu-plugins/functions.php, mu-plugins/search-route.php
更改post type 該為中文名稱
新增graduateProject API
=> add graduateProject api

mu-plugins/functions.php, mu-plugins/search-route-graduateProjects.php, mu-plugins/search-route.php
=> update graduateProject API

mu-plugins/functions.php, mu-plugins/search-route-banner.php, mu-plugins/search-route-graduateProjects.php, mu-plugins/search-route-post.php, mu-plugins/search-route-staff.php, mu-plugins/test.txt
新增 post api
首頁榮譽榜系務公告
系務公告
榮譽榜
等各頁面資料API
=> add post api

mu-plugins/dtd-post-types.php, mu-plugins/functions.php, mu-plugins/search-route-graduateProjects.php, mu-plugins/search-route-staff.php
=> update staff api

src/components/FutureContent/styles.module.scss, src/components/IndexBanner/styles.module.scss, src/store/actions.js
=> Future activity v3

src/styles/pageMargin.scss
=> feat: add pageMargin styles

src/assets/json/indexContent.json, src/components/IndexBanner/index.js, src/components/IndexContent/index.js, src/components/IndexNews/index.js
=> feat: homePage add link

src/components/ActivitiesContent/index.js, src/components/IndexBanner/index.js, src/layouts/Home/index.js
首頁banner link設定、進入首頁置頂、系上活動頁的icon更改
=> Index adjustment

src/layouts/Home/index.js, src/layouts/Home/styles.module.scss
=> fix: homePage scroll to top

src/components/ActivitiesContent/styles.module.scss, src/components/Banner/styles.module.scss, src/components/FutureContent/styles.module.scss, src/components/IndexBanner/styles.module.scss, src/components/IndexNews/index.js, src/layouts/ActivityDetail/styles.module.scss
修改首頁banner高度
系上活動、未來發展scss微調
首頁公告、榮譽榜的groupid改成groupId
=> Adjustment v2

src/assets/json/indexContent.json, src/components/ActivitiesContent/index.js, src/components/IndexContent/index.js, src/layouts/Activities/index.js
=> fix: DTDGroup link

mu-plugins/dtd-post-types.php, mu-plugins/functions.php, mu-plugins/search-route-classProject.php, mu-plugins/search-route-excellentProject.php, mu-plugins/search-route-graduateProject.php
change cooperationProject to  excellentProject
and update api of excellentProject & classProject
=> update api excellent class

src/assets/json/indexContent.json, src/components/ActivitiesNavItem/index.js
=> feat: change homePage indexContent title

src/components/ActivitiesNavItem/index.js, src/uiStore/actions.js
=> feat: activities picture change

src/components/ActivitiesNavbar/styles.module.scss
=> styles: activitiesNav RWD setting

src/layouts/Activities/index.js, src/uiStore/actions.js
=> feat: activitesPage refresh setting

src/components/IndexBannerNews/index.js, src/components/IndexBannerNews/styles.module.scss, src/layouts/Home/index.js, src/store/actions.js, src/store/reducer.js
首頁只有第一次載入會loading，其餘都從reducer取資料
=> Adjustment v14

src/assets/json/DTDActivities.json, src/assets/json/DTDGroup.json, src/assets/json/camp.json, src/assets/json/exhibition.json, src/assets/json/intro.json, src/assets/json/visits.json, src/components/IndexBannerNews/index.js, src/routes/index.js
=> debug: json assets delete / 

src/assets/json/indexContent.json, src/layouts/Activities/index.js
=> debug: ActivitiesPage solve hash problem

src/assets/json/indexContent.json, src/components/IndexContent/index.js
=> feat: Home outside link will show in new page

src/assets/json/indexContent.json, src/layouts/Activities/index.js
=> fix: activities page scroll

src/components/News/index.js, src/layouts/Home/index.js
=> fix: body-scroll-lock disabled on ios

src/components/IndexBannerNews/index.js, src/components/IndexBannerNews/styles.module.scss
=> fix: Home show HTML emoji

src/assets/json/indexContent.json, src/components/IndexContent/index.js, src/components/IndexContent/styles.module.scss
=> feat: homePage add 科學週 link

src/assets/json/indexContent.json, src/components/IndexContent/index.js, src/components/IndexContent/styles.module.scss
=> refacter: homePage 科學週 line feed

src/components/ActivitiesNavItem/index.js
解決系上活動頁面，第二次點擊同個activeItem時，內容消失的問題
=> fix: second time click same activeItem bug
